version: 2.1

orbs:
  python: circleci/python@2.1.1  # Using the official Python orb

jobs:
  build_and_test:
    executor: python/default  # The orb defines this executor
    steps:
      - checkout  # Check out the code
      - python/install-packages:  # This step comes from the orb, handles dependencies
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest -v  # Run the tests with verbose output

workflows:
  version: 2
  python_app_pipeline:
    jobs:
      - build_and_test
