version: 2.1

jobs:
  build_and_test:
    executor: python/default  # Using the default Python executor
    steps:
      - checkout  # Check out the source code
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt  # Make sure all dependencies are installed
      - run:
          name: Run tests
          command: pytest -v  # Run the tests with verbose output

workflows:
  version: 2
  python_app_pipeline:
    jobs:
      - build_and_test
