version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.8  # Use the CircleCI Python 3.8 Docker image
    steps:
      - checkout  # Check out the source code
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt  # Install dependencies from requirements.txt
      - run:
          name: Run tests
          command: pytest -v tests.py # Run the tests with verbose output

workflows:
  version: 2
  python_app_pipeline:
    jobs:
      - build_and_test
